// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADubgnU3_AYEebFudokN8HrEyGzi-mPkQ',
    appId: '1:871716723027:web:4c63c645daf250c55ba9a6',
    messagingSenderId: '871716723027',
    projectId: 'tiktok-cskim',
    authDomain: 'tiktok-cskim.firebaseapp.com',
    storageBucket: 'tiktok-cskim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSfCwCTNy-uGHMAznEKIRqfFP0uO2wE1w',
    appId: '1:871716723027:android:7336804f80b903065ba9a6',
    messagingSenderId: '871716723027',
    projectId: 'tiktok-cskim',
    storageBucket: 'tiktok-cskim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFR618f2WVfwC3EaCZMX4sz7I3ZumOoY',
    appId: '1:871716723027:ios:65193406448cc5ab5ba9a6',
    messagingSenderId: '871716723027',
    projectId: 'tiktok-cskim',
    storageBucket: 'tiktok-cskim.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

}